/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app.sales-orders.index'
import { Route as AppRfqIndexRouteImport } from './routes/_app.rfq.index'
import { Route as AppQuotationsIndexRouteImport } from './routes/_app.quotations.index'
import { Route as AppClientsIndexRouteImport } from './routes/_app.clients.index'
import { Route as AppSalesOrdersSoIdRouteImport } from './routes/_app.sales-orders.$soId'
import { Route as AppRfqIdRouteImport } from './routes/_app.rfq.$id'
import { Route as AppQuotationsIdRouteImport } from './routes/_app.quotations.$id'
import { Route as AppClientsClientIdRouteImport } from './routes/_app.clients.$clientId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/sales-orders/',
  path: '/sales-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqIndexRoute = AppRfqIndexRouteImport.update({
  id: '/rfq/',
  path: '/rfq/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppSalesOrdersSoIdRoute = AppSalesOrdersSoIdRouteImport.update({
  id: '/sales-orders/$soId',
  path: '/sales-orders/$soId',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqIdRoute = AppRfqIdRouteImport.update({
  id: '/rfq/$id',
  path: '/rfq/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIdRoute = AppQuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/quotations/$id': typeof AppQuotationsIdRoute
  '/rfq/$id': typeof AppRfqIdRoute
  '/sales-orders/$soId': typeof AppSalesOrdersSoIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/quotations/': typeof AppQuotationsIndexRoute
  '/rfq/': typeof AppRfqIndexRoute
  '/sales-orders/': typeof AppSalesOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/quotations/$id': typeof AppQuotationsIdRoute
  '/rfq/$id': typeof AppRfqIdRoute
  '/sales-orders/$soId': typeof AppSalesOrdersSoIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/quotations': typeof AppQuotationsIndexRoute
  '/rfq': typeof AppRfqIndexRoute
  '/sales-orders': typeof AppSalesOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/quotations/$id': typeof AppQuotationsIdRoute
  '/_app/rfq/$id': typeof AppRfqIdRoute
  '/_app/sales-orders/$soId': typeof AppSalesOrdersSoIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/quotations/': typeof AppQuotationsIndexRoute
  '/_app/rfq/': typeof AppRfqIndexRoute
  '/_app/sales-orders/': typeof AppSalesOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/clients'
    | '/dashboard'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/clients/$clientId'
    | '/quotations/$id'
    | '/rfq/$id'
    | '/sales-orders/$soId'
    | '/clients/'
    | '/quotations/'
    | '/rfq/'
    | '/sales-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/dashboard'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/clients/$clientId'
    | '/quotations/$id'
    | '/rfq/$id'
    | '/sales-orders/$soId'
    | '/clients'
    | '/quotations'
    | '/rfq'
    | '/sales-orders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/clients/$clientId'
    | '/_app/quotations/$id'
    | '/_app/rfq/$id'
    | '/_app/sales-orders/$soId'
    | '/_app/clients/'
    | '/_app/quotations/'
    | '/_app/rfq/'
    | '/_app/sales-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/': {
      id: '/_app/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfq/': {
      id: '/_app/rfq/'
      path: '/rfq'
      fullPath: '/rfq/'
      preLoaderRoute: typeof AppRfqIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/': {
      id: '/_app/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/sales-orders/$soId': {
      id: '/_app/sales-orders/$soId'
      path: '/sales-orders/$soId'
      fullPath: '/sales-orders/$soId'
      preLoaderRoute: typeof AppSalesOrdersSoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfq/$id': {
      id: '/_app/rfq/$id'
      path: '/rfq/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof AppRfqIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/$id': {
      id: '/_app/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AppQuotationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppQuotationsIdRoute: typeof AppQuotationsIdRoute
  AppRfqIdRoute: typeof AppRfqIdRoute
  AppSalesOrdersSoIdRoute: typeof AppSalesOrdersSoIdRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
  AppRfqIndexRoute: typeof AppRfqIndexRoute
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppQuotationsIdRoute: AppQuotationsIdRoute,
  AppRfqIdRoute: AppRfqIdRoute,
  AppSalesOrdersSoIdRoute: AppSalesOrdersSoIdRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
  AppRfqIndexRoute: AppRfqIndexRoute,
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
